apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
  namespace: ecommerce-namespace
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: myregistrykubernetes.azurecr.io/api-getway-image:3.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: MyLove@1988!
        ports:
        - containerPort: 8080