apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: ecommerce-namespace
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: myregistrykubernetes.azurecr.io/mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "MyLove@1988!"
        - name: MYSQL_DATABASE
          value: "ecommerceproductsdatabase"
        ports:
        - containerPort: 3306
      #   volumeMounts:
      #   - mountPath: /var/lib/mysql
      #     name: mysql-storage
      # volumes:
      # - name: mysql-storage
      #   persistentVolumeClaim:
      #     claimName: mysql-pvc
