apiVersion: apps/v1
kind: Deployment
metadata:
  name: demowebapp-deployment
  labels:
    app: demo-webapi-app
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: demowebapp
  template:
    metadata:
      labels:
        app: demowebapp
    spec:
      containers:
        - name: demowebapp-api
          image: myregistrykubernetes.azurecr.io/demowebapp-api-image:1.0
          ports: 
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
