apiVersion: v1
kind: Service
metadata:
  name: demowebapp-service
spec:
  selector:
    app: demowebapp
  ports:
    - protocol: TCP
      port: 80        # Port exposé par le service
      targetPort: 8080 # Port du conteneur (dans le Pod)
  type: LoadBalancer     # Ou LoadBalancer pour accès externe
